// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cahuydrrayevdydbyphz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhaHV5ZHJyYXlldmR5ZGJ5cGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MjUzODgsImV4cCI6MjA1NTIwMTM4OH0.xwpNCnAlS0JgivKWZv7Lb7XLHjN2LJSeTHGB1jcpXeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);